# Generated by Django 5.0.1 on 2024-02-15 17:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=255)),
                ('cod_disciplina', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TurmaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma_nome', models.CharField(max_length=255, verbose_name='Turma')),
            ],
        ),
        migrations.CreateModel(
            name='PlanejamentoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planejamento_semanal_taxonomia', models.CharField(blank=True, choices=[('Lembrar', 'Lembrar'), ('Entender', 'Entender'), ('Aplicar', 'Aplicar'), ('Análisar', 'Análisar'), ('Avaliar', 'Avaliar'), ('Elaborar', 'Elaborar'), ('Interceder', 'Interceder')], max_length=255, verbose_name='Taxonomias')),
                ('planejamento_semanal_hora_aula', models.CharField(blank=True, max_length=255, verbose_name='Hora Aula')),
                ('planejamento_semanal_dt_inicio', models.DateTimeField(blank=True, verbose_name='Data')),
                ('planejamento_semanal_dt_final', models.DateTimeField(blank=True, null=True, verbose_name='Data')),
                ('planejamento_semanal_descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('registro_planejamento_semanal_dt', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data de Registro')),
                ('planejamento_semanal_enviado', models.BooleanField(blank=True, null=True)),
                ('planejamento_semanal_cod_classroom', models.TextField(blank=True, null=True)),
                ('planejamento_semanal_criador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('planejamento_semanal_disciplina', models.ManyToManyField(to='planejamento_semanal.disciplinamodel')),
                ('planejamento_semanal_turma', models.ManyToManyField(to='planejamento_semanal.turmamodel')),
            ],
        ),
        migrations.AddField(
            model_name='disciplinamodel',
            name='fk_turma',
            field=models.ManyToManyField(to='planejamento_semanal.turmamodel'),
        ),
    ]
