# Generated by Django 5.0.1 on 2024-02-20 19:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='PlanejamentoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planejamento_semanal_criador', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('planejamento_semanal_turma', models.CharField(blank=True, max_length=255, verbose_name='Turma')),
                ('planejamento_semanal_disciplina', models.CharField(blank=True, max_length=255, verbose_name='Disciplina')),
                ('planejamento_semanal_taxonomia', models.CharField(blank=True, max_length=255, verbose_name='Taxonomia')),
                ('planejamento_semanal_hora_aula', models.CharField(blank=True, max_length=255, verbose_name='Hora Aula')),
                ('planejamento_semanal_dt_inicio', models.DateTimeField(blank=True, verbose_name='Data')),
                ('planejamento_semanal_dt_final', models.DateTimeField(blank=True, null=True, verbose_name='Data')),
                ('planejamento_semanal_descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('registro_planejamento_semanal_dt', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data de Registro')),
                ('planejamento_semanal_enviado', models.BooleanField(blank=True, null=True)),
                ('planejamento_semanal_cod_classroom', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPlanejamentoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_planejamento_semanal', models.CharField(max_length=255, verbose_name='Email')),
                ('registro_planejamento_semanal_dt', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data de Registro')),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_taxonomia', models.CharField(blank=True, max_length=20, verbose_name='Taxonomia')),
            ],
            options={
                'verbose_name': 'Taxonomia',
                'verbose_name_plural': 'Taxonomias',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_serie', models.CharField(max_length=255, verbose_name='Série')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planejamento_semanal.instituicao', verbose_name='Instituição')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(blank=True, max_length=100, verbose_name='Disciplina')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planejamento_semanal.serie', verbose_name='Série')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_turma', models.CharField(max_length=100, unique=True, verbose_name='Turma')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planejamento_semanal.serie', verbose_name='Série')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
    ]
