# Generated by Django 5.0.1 on 2024-02-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento_semanal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamentomodel',
            name='planejamento_semanal_hora_aula',
            field=models.IntegerField(blank=True, verbose_name='Hora Aula'),
        ),
    ]
